
// main.cpp - DO NOT EDIT THIS FILE!

#include <iostream>
#include <conio.h>

#include "Circle.h"
#include "Triangle.h"

using namespace std;

int main()
{
	double dSideA, dSideB, dSideC;
	cout << "Please enter the side lengths of the triangle: " << endl;
	cout << "Side A: ";
	cin >> dSideA;
	cout << "Side B: ";
	cin >> dSideB;
	cout << "Side C: ";
	cin >> dSideC;

	Shape *triangle = new Triangle(dSideA, dSideB, dSideC);
	triangle->Display();

	cout << endl << endl;

	double dRadius = 0;
	cout << "Please enter the radius of the circle: ";
	cin >> dRadius;

	Shape *circle = new Circle(dRadius);
	circle->Display();

	_getch();
	return 0;
}