
// Triangle.cpp - DO NOT EDIT THIS FILE!

#include <math.h>

#include "Triangle.h"


Triangle::Triangle(double sideA, double sideB, double sideC)
{
	SetSideA(sideA);
	SetSideB(sideB);
	SetSideC(sideC);
}


void Triangle::SetSideA(double size)
{ 
	if (size > 0) m_sideA = size;
	else m_sideA = 1;
}


void Triangle::SetSideB(double size)
{
	if (size > 0) m_sideB = size;
	else m_sideB = 1;
}


void Triangle::SetSideC(double size)
{
	if (size > 0) m_sideC = size;
	else m_sideC = 1;
}


double Triangle::GetArea()
{
	double p = GetPerimeter() / 2;
	return sqrt(p * (p - m_sideA) * (p - m_sideB) * (p - m_sideC));
}


double Triangle::GetPerimeter()
{
	return m_sideA + m_sideB + m_sideC;
}